version: "3.9"
services:
  csv:
    image: infracloudio/csvserver:latest
    environment:
    - CSVSERVER_BORDER=Orange
    ports:
      - "9300:9393"
    volumes:
      - "/csvserver:/csvserver"
  prom:
    image: prom/prometheus:v2.22.0
    ports:
      - "9090:9090"
    volumes:
      - "/prometheus.yml:/etc/prometheus/prometheus.yml"